/* Generated By:JJTree: Do not edit this line. ASTBoolOpp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicl.main;

public
class ASTBoolOpp extends SimpleNode {
  public ASTBoolOpp(int id) {
    super(id);
  }

  public ASTBoolOpp(BasicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0dcf1756b504d1326f02ebb50f627b83 (do not edit this line) */
