/* Generated By:JJTree: Do not edit this line. ASTFunction_Decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicl.main;

public
class ASTFunction_Decl extends SimpleNode {
  public ASTFunction_Decl(int id) {
    super(id);
  }

  public ASTFunction_Decl(BasicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=13125c99782279e475fcf5b9b0842597 (do not edit this line) */
