/* Generated By:JavaCC: Do not edit this line. BasicLTreeConstants.java Version 5.0 */
package basicl.main;

public interface BasicLTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTCONSTDECL = 3;
  public int JJTFUNCTION_DECL = 4;
  public int JJTFUNCTION_BODY = 5;
  public int JJTPARAMS = 6;
  public int JJTTYPE = 7;
  public int JJTMAIN = 8;
  public int JJTASSIGN = 9;
  public int JJTIF = 10;
  public int JJTWHILE = 11;
  public int JJTADD = 12;
  public int JJTMULT = 13;
  public int JJTADDOP = 14;
  public int JJTMULTOP = 15;
  public int JJTBOOLOPP = 16;
  public int JJTCONDITION = 17;
  public int JJTIDENT_LIST = 18;
  public int JJTARG_LIST = 19;
  public int JJTID = 20;
  public int JJTNUM = 21;
  public int JJTBOOL = 22;
  public int JJTREAL = 23;
  public int JJTFUNCTIONCALL = 24;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Decl",
    "ConstDecl",
    "Function_Decl",
    "Function_body",
    "Params",
    "Type",
    "Main",
    "Assign",
    "If",
    "While",
    "Add",
    "Mult",
    "AddOp",
    "MultOp",
    "BoolOpp",
    "Condition",
    "Ident_list",
    "Arg_list",
    "Id",
    "Num",
    "Bool",
    "Real",
    "FunctionCall",
  };
}
/* JavaCC - OriginalChecksum=d7c5e0a727064f5b42d770d46073ff94 (do not edit this line) */
